# Lecture 03 Python / Jupyter Tutorial — Integrated Tutorial & Assignment
**Course:** EMS-Bat

<div class="alert alert-block alert-info">

**TASK 01** 

**Name:** Max Mustermann

### Preface: The very basics for good Python style

- **Comment your code** – Write clear comments (using `# ...`) that explain *what* your code does and *why*.
- **Imports at the top** – Place `import` statements and constants at the beginning of the notebook or script.
- **Structure your code** – Use `functions` and logically connected blocks.
- **Readability over brevity** – For comments, variables, and code: it is better to be a bit more explicit if it makes things easier to understand and maintain!

In [1]:
# this is a "comment line" INSIDE a CODE block!
# you can EXECUTE this block and it will run the code, but the comment line will be ignored by python
# following import statements allow us to use the functionality of these libraries in our code
# numpy is a library for numerical computations, pandas is for data manipulation and analysis, plotly is for creating interactive visualizations, and math provides mathematical functions.

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from math import pi

**This is a "MARKDOWN block"**  
Text / notes / helpful information. **Not** Python code, but explanatory text.
Similar to:
- a comment field in a Matlab "Live Script"
- a "text box" in an Excel workbook

Markdown blocks can contain different kinds of formatting, e.g. *italic* or **bold** text.
For formulas, *LaTeX* commands are useful, for example: $$ \sum_{t}(p^{in}_t \cdot k^{buy}) \cdot  \Delta t $$

## Work with Jupyter & Deepnote

- **Run a cell:** `Shift + Enter`
- **Add a cell:** `+ Code` / `+ Markdown`
- **Restart runtime / kernel:** if variables feel “stuck” or imports have changed
- **Markdown vs. code cells:** use Markdown for explanations and code cells for executable Python
- **Best practice:** run notebooks from top to bottom to avoid hidden state issues

## Data types and variables

Variables are core elements of programming languages. **Use consistent and meaningful names.**

- Variables should start with lowercase letters.
- For variables, use descriptive names in *lowercase_with_underscores*, e.g. `total_power`, or *camelCase*, e.g. `totalPower`.
- In contrast, use `UPPER_CASE` for constants, e.g. `FARADY_CONSTANT = 26.8`.

In [2]:
# code block - all the below (but commented out blocks) are pyhton code blocks
myVariable1 = 10
myVariable2 = 20
sum_of_variables = myVariable1 + myVariable2
print("The sum of the variables is:", sum_of_variables)

The sum of the variables is: 30

## Short Python warm-up

In [3]:
# Variables and arithmetic
a = 10
b = 3
a / b

3.3333333333333335

**The execution order matters:** If you edit cells *above*, this will change stored values (see below). Check this by running the cells below again!

In [4]:
print(a)
a = a + 1
print(a)

10
11

<div class="alert alert-block alert-info">

**TASK 02**:

- create a markdown block with this text: "Here comes a simple division"
- create a code block below and divide variable `c = 3` by `d = 9`
- print the result

</div>

<div class="alert alert-block alert-success">

#### Solution
Here comes a simple division

In [5]:
## SOLUTION

# Variables and arithmetic
c = 3
d = 9
result = c / d
print(result)

0.3333333333333333

**Data types**


Variables are stored in different types, which tell the computer what kind of value is being used. This allows data to be stored and processed efficiently.

- 🔢 Integer → 1
- 🔢 Float → 2.5
- 🔤 String → "Hello"
- ✅ Boolean → True / False

In [6]:
# implementation of data types in python (implicit)
int1=1
float1=2.5
string1="Hello"
bool1=True

# implementation of data types in python (explicit)
float2 = float(3)
int2 = int(4.5)

Use the `type()` function to identify the data type of a variable.

In [7]:
type(int1)

int

In [8]:
type(float2)

float

### Data type conversion

As shown above, in Python it is not necessary to declare the data type of a variable or an object explicitly. Python automatically recognizes the data type. Sometimes, however, it is necessary to convert one data type into another. To do this, simply write the variable in parentheses after the target data type, e.g. `float(10)` converts the integer `10` into the float `10.0`.

The function `input()` returns the user’s input as a string. However, if numerical values are requested and should then be processed further, you must convert the data type accordingly.

Test the following expressions. You can always display the type of a variable with `type()` as well.

In [9]:
x = "123"
type(x)

str

In [10]:
3 * x

'123123123'

In [11]:
type(x)

str

In [12]:
x = int(x)
3 * x

369

In [13]:
type(x)

int

### input command

In [14]:
name = input("What is your name? ")
print("Hello ", name + "!")
year_of_birth = int(input("In which year were you born? "))
age = 2023 - year_of_birth
print("You are approximately", age, "years old.")

Hello  Max Mustermann!
You are approximately 33 years old.

### Note: Python is case sensitive (!)

In [15]:
myVariable1 = 10
myVARIABLE1 = 20

### Inspecting variables

In [16]:
%whos

Variable           Type        Data/Info
----------------------------------------
a                  int         11
age                int         33
b                  int         3
bool1              bool        True
c                  int         3
d                  int         9
float1             float       2.5
float2             float       3.0
go                 module      <module 'plotly.graph_obj<...>ph_objects\\__init__.py'>
int1               int         1
int2               int         4
make_subplots      function    <function make_subplots at 0x0000026EAD4431A0>
myVARIABLE1        int         20
myVariable1        int         10
myVariable2        int         20
name               str         Max Mustermann
np                 module      <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
pd                 module      <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
pi                 float       3.141592653589793
px                 module      <module 'plotly.express' <...>y\\express\\__init__.py'>
result             float       0.3333333333333333
string1            str         Hello
sum_of_variables   int         30
x                  int         123
year_of_birth      int         1990

### Variable Explorer

In Deepnote (similar to many other IDEs), variables can also be viewed in the **Variable Explorer**.

![Deepnote_IDE](../figures/deepnote_variable_explorer.png)

# Loops
## IF statement

![If statement](../figures/loops_if.png)

In [17]:
i = int(input("Enter an integer value: "))
print("You entered:", i)

if i == 0: # if the value of i is equal to 0, then execute the following block of code
    print("You entered zero.")
elif i%2 == 0: # % is the modulo operator, it gives the remainder of the division of i by 2. If the remainder is 0, then i is even.
    print("You entered an even number.")
else: # if i is not 0 and not even, then it must be odd.
    print("You entered an odd number.")

You entered: 123
You entered an odd number.

## while loop
![while loop](../figures/loops_while.png)

In [18]:
while i < 10: # while the value of i is less than 10, execute the following block of code
    print("Current value of i:", i)
    i += 1 # this is equivalent to i = i + 1, it increments the value of i by 1 in each iteration of the loop

### Functions

- perform tasks
- are either defined by the user or provided as built-in or predefined functions (e.g. through package imports)
- usually start with a lowercase letter
- can receive **inputs** (*arguments*) — these are comma-separated and provided in brackets *directly* after the function name
- can have **return values** — these are specified using the `return` command

In [19]:
# A simple function to divide two numbers
def my_division(input_1, input_2): # this function accepts two inputs, input_1 and input_2, which are the numbers to be divided. The function will perform the division and return the result.
    """Divide two numbers."""
    my_division_result = input_1 / input_2
    print("The result of the division is:", my_division_result)
    return my_division_result # this line allows the function to return the result of the division, which can be stored in a variable or used in further calculations

In [20]:
my_division(5, 2.5)

The result of the division is: 2.0

2.0

In [21]:
my_division(a, b)

The result of the division is: 3.6666666666666665

3.6666666666666665

<div class="alert alert-block alert-info">

**TASK 03**: (all)

- create a code block with a function called `energy_kwh`, which reads the inputs `power_W` in watts and `duration_s` in seconds and returns the amount of energy in kilowatt hours
- test your function with example values (e.g. 5,000 W for 3,600 s)

</div>

In [22]:
## Solution 
# A simple function
def energy_kwh(power_w, duration_s):
    """Energy in kWh if power is in W and duration in s."""
    return power_w /1000 * duration_s / 3600

energy_kwh(5000, 3600)

5.0

### Recursive function example: factorial

Details on the factorial function can be found here, for example: [Factorial](https://de.wikipedia.org/wiki/Fakult%C3%A4t_(Mathematik))

In [23]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

# Example
print(factorial(5))  # 120

120

## Default values in functions

In [24]:
def hello(name1='Max Mustermann', name2='Erika Müller'):
  print('Hallo', name1, 'und', name2, '!')

hello()

hello('Paul Smith', 'Anna Brown')

hello('Paul Smith')

Hallo Max Mustermann und Erika Müller !
Hallo Paul Smith und Anna Brown !
Hallo Paul Smith und Erika Müller !

## Local and global variables in functions

In [25]:
def test_loc_glob():
    i = 42 # this variable i is LOCAL to the function test_loc_glob, it is different from the variable i defined outside the function
    s = 'I am a string INSIDE the function.' # this variable s is also LOCAL to the function test_loc_glob, it is different from any variable s defined outside the function
    print(s)
    print(i)

s = 'I am a string OUTSIDE - in the program code.'
i = 7 # this variable i is OUTSIDE the function test_loc_glob, it is different from the variable i defined inside the function

print("Before calling the function:")
test_loc_glob()

print("After calling the function:")    
print(s)
print(i)

Before calling the function:
I am a string INSIDE the function.
42
After calling the function:
I am a string OUTSIDE - in the program code.
7

*** If a variable name defined in a function is to be used both in a function and in the program code, this variable can be defined as a “global” variable by using the keyword `global` followed by the variable name (`i` in the example). Mixing local and global variables with the same name within a function does not work and results in an error. If `s` is to be changed within the function in the third example, `s` must be defined as a global variable before the first `print()` call.

## Formatted output
Engineers usually write numerical data into files. String objects have the attribute format, which makes it easy to format numerical data. The logic of string formatting is based on placeholder fields enclosed in curly braces. Text outside the placeholder fields is not formatted.

<div class="alert alert-block alert-info">

**TASK 04**: 

Test the following expressions in Python by creating  & executing one code block per command:

- pi
- "{}; {}".format(pi, -pi)
- "{1}, {0}".format(pi, -pi)
- "{1:.3f}, {0:.3f}".format(pi, -pi)
- "{:.3e}, {:.3e}".format(pi, -pi)
- "{:+.3}, {:+.3}".format(pi, -pi)
- "{: .3}, {: .3}".format(pi, -pi)
- answer = 6 * 7
- "{} is the answer to all questions.".format(answer)
- euro = 10
- cent = 95
- "Your purchase costs {0},{1} euros.".format(euro, cent)

</div>

In [26]:
pi

3.141592653589793

In [27]:
"{}; {}".format(pi, -pi)

'3.141592653589793; -3.141592653589793'

In [28]:
"{1}, {0}".format(pi, -pi)

'-3.141592653589793, 3.141592653589793'

In [29]:
"{1:.3f}, {0:.3f}".format(pi, -pi)

'-3.142, 3.142'

In [30]:
"{:.3e}, {:.3e}".format(pi, -pi)

'3.142e+00, -3.142e+00'

In [31]:
"{:+.3}, {:+.3}".format(pi, -pi)

'+3.14, -3.14'

In [32]:
"{: .3}, {: .3}".format(pi, -pi)

' 3.14, -3.14'

In [33]:
answer = 6 * 7
"{} is the answer to all questions.".format(answer)

'42 is the answer to all questions.'

In [34]:
euro = 10
cent = 95
"Your purchase costs {0},{1} euros.".format(euro, cent)

'Your purchase costs 10,95 euros.'

# Compound data types

Below is a short overview of the most important compound data types: **Dictionary**, **List**, and **DataFrame**

# Lists

Lists are ordered collections of values. They are mutable and are used very frequently in Python.

## Reference or copy?
For lists and DataFrames, it is important to understand whether two variables point to **the same object** or whether a **new copy** was actually created.

### Example: reference vs. copy for lists

- In principle, variables can be passed in two different ways in any programming language: by copy or by reference. A reference can be understood as a pointer to a specific location in memory. In C, variables are generally passed by copy. In that case, only the variable `newList` would be changed in the example, but not the variable `a`.
- In Python, variables are generally handled as references. Therefore, the variables `a` and `newList` are just two pointers to the same memory area. Both pointers can be used to modify the same data. Passing by reference is significantly more performant than passing by copy, especially for larger objects.
- This topic is important because changes made through a reference can **unexpectedly** affect other variables.

In [35]:
# Reference: both variables point to the same list
list_a = ['T', 'a', 'n', 'k']
list_b = list_a
list_b[0] = 'B'

print("list_a:", list_a)
print("list_b:", list_b)

list_a: ['B', 'a', 'n', 'k']
list_b: ['B', 'a', 'n', 'k']

If you want to create a copy in Python, you can use the `.copy()` function.

**Remember:** An unintended reference is a common source of errors in data analysis workflows.

In [36]:
# Copy: list_b is a reference, but not a copy!
list_a = ['T', 'a', 'n', 'k']
list_b = list_a.copy()
list_b[0] = 'B'
print("list_a:", list_a)
print("list_b:", list_b)
list_1 = [1, 2, 4, 5, 6]
list_1.insert(2, 3) # insert 3 at index 2 - note that indexing strats with 0 not 1 (!)

print("list_1:", list_1)
list_1.insert(0, 0) # insert 0 at index 0
print("list_1:", list_1)

list_a: ['T', 'a', 'n', 'k']
list_b: ['B', 'a', 'n', 'k']
list_1: [1, 2, 3, 4, 5, 6]
list_1: [0, 1, 2, 3, 4, 5, 6]

## Simple operations with lists

- Operations to append or delete items in a list

In [37]:
list_a.append('e')
list_a.append('n')
print(list_a)
list_a.remove('n') # removes the first occurrence of 'n' in the list
print(list_a)

['T', 'a', 'n', 'k', 'e', 'n']
['T', 'a', 'k', 'e', 'n']

In [79]:
list = [2.3, 'a', 5, 14.7, 'w', 'xyz', 33, '15', 'w', 9.4] # this is a list with mixed data types: floats, strings, and integers
print("Original list:", list)

Original list: [2.3, 'a', 5, 14.7, 'w', 'xyz', 33, '15', 'w', 9.4]

<div class="alert alert-block alert-info">

**TASK 05**: 

Test the following expressions in separate code blocks and display the list after each step:

- list.remove('w')
- list.pop(3)
- del list[-1]
- list[0:2] = []

In [80]:
## Solution
print("Original list:", list)
list.remove('w')
print("Modified list:", list)
list.pop(3)
print("Modified list:", list)
del list[-1]
print("Modified list:", list)
list[0:2] = []

print("Modified list:", list)

Original list: [2.3, 'a', 5, 14.7, 'w', 'xyz', 33, '15', 'w', 9.4]
Modified list: [2.3, 'a', 5, 14.7, 'xyz', 33, '15', 'w', 9.4]
Modified list: [2.3, 'a', 5, 'xyz', 33, '15', 'w', 9.4]
Modified list: [2.3, 'a', 5, 'xyz', 33, '15', 'w']
Modified list: [5, 'xyz', 33, '15', 'w']


Create a new code block with a list named `values` containing the entries `1, 2, 3, 4, 5`.

Now create a new list `results` that contains the squares of each entry of the list `values`, and print the contents of `results`.

In [40]:
values = [1, 2, 3, 4, 5]

In [41]:
# for-loop
results = []
for v in values:
    results.append(v**2)
print(results)

[1, 4, 9, 16, 25]

In [42]:
# List comprehension
results = [v**2 for v in values]
print(results)

[1, 4, 9, 16, 25]

<div class="alert alert-block alert-warning">
Note:

- Functions use parentheses (“round brackets”), e.g. `myFunction(arg1, arg2)`.
- Lists use square brackets, e.g. `myList[1]`.
- List comprehensions allow more compact formulations than `for` loops.

## Iterables

We can iterate over many types of *iterables*.

In [43]:
list_iterable = [10, 20, 30, 40, 50]
print("Iterating over a list:")
for n in list_iterable:
    print(n)

print ('\n')
string_iterable = 'EMS-Bat'
print("Iterating over a string:")
for c in string_iterable:
    print(c)

print ('\n')
range_iterable = range(1, 6)
print("Iterating over a range:")    
for m in range_iterable:
    print(m)

Iterating over a list:
10
20
30
40
50


Iterating over a string:
E
M
S
-
B
a
t


Iterating over a range:
1
2
3
4
5

<div class="alert alert-block alert-info">

**TASK 06**: 

Calculate the [Fibonacci sequence](https://en.wikipedia.org/wiki/Fibonacci_sequence) and fill it with 50 elements.
- in a first code block, define a list named `fibonacciList` and calculate the values through a loop

</div>

In [44]:
## solution

fibonacciList = [0, 1]
for c in range(50):
    next_fib = fibonacciList[-1] + fibonacciList[-2]
    fibonacciList.append(next_fib)
print(fibonacciList)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074]

<div class="alert alert-block alert-info">

**TASK 07**: 

- in a second code block, define a function named `fibonacciFunction` which automatically calculates the Fibonacci number through a *recursive function call*

</div>

In [45]:
## solution 

def fibonacciFunction(n):
    if n <= 1:
        return n
    return fibonacciFunction(n-1) + fibonacciFunction(n-2)

In [46]:
# execute this command and time the execution of the function to see how long it takes to compute the 40th Fibonacci number
# if the code fails to execute with Deepnote, try lower numbers e.g. fibonacciFunction(30)
fibonacciFunction(40)

102334155

<div class="alert alert-block alert-info">

**TASK 08**: 

- compare the runtime of `fibonacciFunction(40)` with `fibonacciList`, which calculates 40 values
- create a markdown cell and explain why `fibonacciList` is computationally superior to `fibonacciFunction`
- the ratio of two consecutive Fibonacci numbers converges to the golden ratio. Approximate this value using the existing list formulation (`fibonacciList`)
- plot the values of this list using *Plotly Express* (as explained later in this notebook)

In [47]:
## solution 
goldenCut = []
for c in range(2,50):
    goldenCut.append(fibonacciList[c]/fibonacciList[c-1])
print(goldenCut)

[1.0, 2.0, 1.5, 1.6666666666666667, 1.6, 1.625, 1.6153846153846154, 1.619047619047619, 1.6176470588235294, 1.6181818181818182, 1.6179775280898876, 1.6180555555555556, 1.6180257510729614, 1.6180371352785146, 1.618032786885246, 1.618034447821682, 1.6180338134001253, 1.618034055727554, 1.6180339631667064, 1.6180339985218033, 1.618033985017358, 1.6180339901755971, 1.618033988205325, 1.618033988957902, 1.6180339886704431, 1.6180339887802426, 1.618033988738303, 1.6180339887543225, 1.6180339887482036, 1.6180339887505408, 1.6180339887496482, 1.618033988749989, 1.618033988749859, 1.6180339887499087, 1.6180339887498896, 1.618033988749897, 1.618033988749894, 1.6180339887498951, 1.6180339887498947, 1.618033988749895, 1.618033988749895, 1.618033988749895, 1.618033988749895, 1.618033988749895, 1.618033988749895, 1.618033988749895, 1.618033988749895, 1.618033988749895]

In [84]:
## Solution 
fig = px.line(y=goldenCut, markers=True)
fig.update_layout(title='Golden Cut Ratio from Fibonacci Sequence',
                    xaxis_title='Index',
                    yaxis_title='Golden Cut Ratio')
fig.show()

<div class="alert alert-block alert-success">

#### Solution

A Fibonacci list in Python is faster because it computes the values iteratively and therefore has no redundant recursive calls like the recursive Fibonacci function, which significantly reduces the runtime

## Dictionaries
Dictionaries store **key-value pairs**. They are very useful in data analytics, for example for configurations, mappings, or metadata.

In [49]:
# Dictionary example
battery_config = {
    "capacity_kwh": 120,
    "max_power_kw": 60,
    "efficiency": 0.94,
}

print(battery_config)
print("Capacity:", battery_config["capacity_kwh"], "kWh")

{'capacity_kwh': 120, 'max_power_kw': 60, 'efficiency': 0.94}
Capacity: 120 kWh

In [50]:
# Dictionary methods
battery_config["max_Crate"] = "2C"
print(battery_config.keys())
print(battery_config.get("max_Crate"))
    
print(battery_config.get("owner"))

dict_keys(['capacity_kwh', 'max_power_kw', 'efficiency', 'max_Crate'])
2C
None

# DataFrames

## Pandas DataFrames for time series

A **DataFrame** is like an Excel table, but controllable through code.

In *MATLAB*, a `table` has a similar function (e.g. `T = table([1;2;3], ["A";"B";"C"], [true;false;true], 'VariableNames', {'ID', 'Name', 'Valid'})`).

In this course, we use DataFrames to process *time series* such as:

- load (kW)
- PV power (kW)
- electricity price (€/kWh)
- temperature (°C)

In [51]:
# Create a small DataFrame from a dictionary
sensor_data = {
    "sensor": ["S1", "S2", "S3"],
    "voltage_v": [401.2, 398.7, 403.1],
    "current_a": [15.2, 14.8, 15.5],
}

sensor_df = pd.DataFrame(sensor_data)

In [52]:
sensor_df

  sensor  voltage_v  current_a
0     S1      401.2       15.2
1     S2      398.7       14.8
2     S3      403.1       15.5

We now define a second DataFrame `df`. It is a **synthetic** dataset, so everything runs without an external file. It contains four time-series signals named `p_load_kw`, `p_pv_kw`, `price_eur_per_kwh`, and `temperature_c`.

In [53]:
# 365 days, 15-min resolution
idx = pd.date_range("2025-01-01", periods=365*24*4, freq="15min")

# time vectors
t_day = (idx.hour + idx.minute/60) / 24          # fraction of day [0..1]
t_year = np.linspace(0, 2*np.pi, len(idx))       # slow annual variation

# PV: DAILY sine pattern (0 at night, peak at noon)
pv_daily = np.sin(2*np.pi*t_day - np.pi/2)
pv_kw = np.clip(3.0 * pv_daily, 0, None)

# Load: daily variation + small annual variation + noise
load_kw = (
    2.0
    + 0.6*np.sin(2*np.pi*t_day)                 # daily oscillation
    + 0.3*np.sin(t_year)                        # slow yearly modulation
    + 0.2*np.random.randn(len(idx))             # noise
)

# Price: slower oscillation + noise
price = (
    0.25
    + 0.05*np.sin(t_year)                       # annual cycle
    + 0.02*np.random.randn(len(idx))
)

# Temperature: daily and seasonal variation
temperature_c = (
    12
    + 8*np.sin(t_year - 0.8)
    + 4*np.sin(2*np.pi*t_day - np.pi/3)
    + 0.8*np.random.randn(len(idx))
)

df = pd.DataFrame({
    "p_load_kw": load_kw,
    "p_pv_kw": pv_kw,
    "price_eur_per_kwh": price,
    "temperature_c": temperature_c,
}, index=idx)

<div class="alert alert-block alert-info">

**TASK 09**: 

- apply all functions `head()`, `tail()`, `shape`, `columns`, `info()`, and `describe()` to the dataframe named `df` in new code blocks below and execute them one by one
- create a markdown cell after executing the commands and explain in your own words what these functions show

</div>

In [54]:
# a first example for you...
df.head()

                     p_load_kw  p_pv_kw  price_eur_per_kwh  temperature_c
2025-01-01 00:00:00   2.077939      0.0           0.278070       2.762041
2025-01-01 00:15:00   2.212796      0.0           0.235068       1.998516
2025-01-01 00:30:00   1.787725      0.0           0.252774       3.471822
2025-01-01 00:45:00   2.330104      0.0           0.240243       3.405629
2025-01-01 01:00:00   1.940196      0.0           0.213892       4.134063


## Solution
- The function call `head()` shows (describe in your words)
...

In [55]:
## SOLUTION
df.shape

(35040, 4)

## Solution
- The function call `shape` shows (describe in your words)
...

In [56]:
## SOLUTION
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 35040 entries, 2025-01-01 00:00:00 to 2025-12-31 23:45:00
Freq: 15min
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   p_load_kw          35040 non-null  float64
 1   p_pv_kw            35040 non-null  float64
 2   price_eur_per_kwh  35040 non-null  float64
 3   temperature_c      35040 non-null  float64
dtypes: float64(4)
memory usage: 1.3 MB

## Solution
- The function call `info()` shows (describe in your words)
...

In [57]:
## SOLUTION
df.describe()

          p_load_kw       p_pv_kw  price_eur_per_kwh  temperature_c
count  35040.000000  3.504000e+04       35040.000000   35040.000000
mean       2.001715  9.545887e-01           0.249985      12.002015
std        0.513290  1.157065e+00           0.040600       6.378068
min        0.583147  0.000000e+00           0.123208      -2.120460
25%        1.607489  0.000000e+00           0.217293       6.951757
50%        1.999467  1.836970e-16           0.249908      11.998379
75%        2.395516  2.121320e+00           0.283061      17.041351
max        3.470679  3.000000e+00           0.365486      26.239983

## Solution
- The function call `describe()` shows (describe in your words)
...

<div class="alert alert-block alert-success">

## Inspecting the dataframe `df`

In the new code blocks below, I applied the functions and attributes `head()`, `tail()`, `shape`, `columns`, `info()`, and `describe()` to the dataframe `df` and executed them one by one.

### What these functions show

- `df.head()` shows the first rows of the dataframe. It is useful for getting a quick first look at the data and checking whether the import worked correctly.
- `df.tail()` shows the last rows of the dataframe. This helps to inspect how the dataframe ends and whether the final entries look reasonable.
- `df.shape` returns the size of the dataframe as `(rows, columns)`. It tells us how many observations and variables are contained in `df`.
- `df.columns` lists the column names of the dataframe. This is helpful to see which variables are available and how they are named.
- `df.info()` gives a compact summary of the dataframe. It shows the index range, the column names, the number of non-missing values, the data types, and the memory usage.
- `df.describe()` provides statistical summary values for the numerical columns. It typically shows the count, mean, standard deviation, minimum, quartiles, and maximum.

### Purpose

These commands are basic tools for exploring a dataframe. Together, they help to understand the structure, content, and quality of the data before starting further analysis or visualization.

### 3.2 Selecting columns and creating new columns

- Single column: `sensor_df["voltage_v"]`
- Multiple columns: `sensor_df[["voltage_v", "current_a"]]`
- New column: `sensor_df["power_kw"] = ...`

### Important practical examples with DataFrames
These are some very typical operations that you will need all the time in data analysis.

In [58]:
# Create new columns in the DataFrame
sensor_df["power_kw"] = sensor_df["voltage_v"] * sensor_df["current_a"] / 1000
sensor_df["status"] = ["ok", "ok", "check"]
sensor_df

  sensor  voltage_v  current_a  power_kw status
0     S1      401.2       15.2   6.09824     ok
1     S2      398.7       14.8   5.90076     ok
2     S3      403.1       15.5   6.24805  check

In [59]:
# Sort and filter
sensor_df.sort_values("power_kw", ascending=False)

  sensor  voltage_v  current_a  power_kw status
2     S3      403.1       15.5   6.24805  check
0     S1      401.2       15.2   6.09824     ok
1     S2      398.7       14.8   5.90076     ok

<div class="alert alert-block alert-info">

**TASK 10**:

- For the dataframe `df`, define a new column named `"p_res_kw"` as the difference between load and PV, and show the first 5 rows of the three columns `"p_load_kw"`, `"p_pv_kw"`, and `"p_res_kw"`.

</div>

In [85]:
## Solution 
df["p_res_kw"] = df["p_load_kw"] - df["p_pv_kw"]
df[["p_load_kw", "p_pv_kw", "p_res_kw"]].head(50)

                     p_load_kw   p_pv_kw  p_res_kw
2025-01-01 00:00:00   2.077939  0.000000  2.077939
2025-01-01 00:15:00   2.212796  0.000000  2.212796
2025-01-01 00:30:00   1.787725  0.000000  1.787725
2025-01-01 00:45:00   2.330104  0.000000  2.330104
2025-01-01 01:00:00   1.940196  0.000000  1.940196
2025-01-01 01:15:00   2.012238  0.000000  2.012238
2025-01-01 01:30:00   2.436228  0.000000  2.436228
2025-01-01 01:45:00   2.223754  0.000000  2.223754
2025-01-01 02:00:00   1.963906  0.000000  1.963906
2025-01-01 02:15:00   2.485482  0.000000  2.485482
2025-01-01 02:30:00   2.336340  0.000000  2.336340
2025-01-01 02:45:00   2.518412  0.000000  2.518412
2025-01-01 03:00:00   2.333960  0.000000  2.333960
2025-01-01 03:15:00   2.435743  0.000000  2.435743
2025-01-01 03:30:00   2.500175  0.000000  2.500175
2025-01-01 03:45:00   2.566029  0.000000  2.566029
2025-01-01 04:00:00   2.364842  0.000000  2.364842
2025-01-01 04:15:00   2.228244  0.000000  2.228244
2025-01-01 04:30:00   2.750257  0.000000  2.750257
2025-01-01 04:45:00   2.777520  0.000000  2.777520
2025-01-01 05:00:00   2.730266  0.000000  2.730266
2025-01-01 05:15:00   2.596511  0.000000  2.596511
2025-01-01 05:30:00   2.711606  0.000000  2.711606
2025-01-01 05:45:00   2.538862  0.000000  2.538862
2025-01-01 06:00:00   2.657890  0.000000  2.657890
2025-01-01 06:15:00   2.515161  0.196209  2.318951
2025-01-01 06:30:00   2.660165  0.391579  2.268586
2025-01-01 06:45:00   2.496547  0.585271  1.911276
2025-01-01 07:00:00   2.420379  0.776457  1.643922
2025-01-01 07:15:00   2.255780  0.964318  1.291462
2025-01-01 07:30:00   2.191673  1.148050  1.043622
2025-01-01 07:45:00   2.369346  1.326866  1.042480
2025-01-01 08:00:00   2.460289  1.500000  0.960289
2025-01-01 08:15:00   2.439281  1.666711  0.772570
2025-01-01 08:30:00   2.590564  1.826284  0.764280
2025-01-01 08:45:00   2.519526  1.978037  0.541488
2025-01-01 09:00:00   2.470896  2.121320  0.349576
2025-01-01 09:15:00   2.667178  2.255519  0.411658
2025-01-01 09:30:00   2.346961  2.380060 -0.033099
2025-01-01 09:45:00   2.314368  2.494409 -0.180041
2025-01-01 10:00:00   2.256332  2.598076 -0.341744
2025-01-01 10:15:00   2.018788  2.690618 -0.671830
2025-01-01 10:30:00   2.477289  2.771639 -0.294350
2025-01-01 10:45:00   2.202699  2.840790 -0.638091
2025-01-01 11:00:00   2.238218  2.897777 -0.659560
2025-01-01 11:15:00   2.098763  2.942356 -0.843593
2025-01-01 11:30:00   1.965838  2.974335 -1.008496
2025-01-01 11:45:00   2.088026  2.993577 -0.905550
2025-01-01 12:00:00   2.137889  3.000000 -0.862111
2025-01-01 12:15:00   2.074676  2.993577 -0.918901

### 3.3 Filtering (boolean indexing)

Examples:
- Filtering by a value condition
- Filtering by a time window using an index of type `DatetimeIndex`

In [61]:
# Filter: PV surplus moments are where residual load is negative (p_res < 0)
df_pv_surplus = df[df["p_res_kw"] < 0]
df_pv_surplus.head()

,p_load_kw,p_pv_kw,price_eur_per_kwh,temperature_c,p_res_kw
2025-01-01 09:30:00,2.346961,2.380060,0.239547,8.655806,-0.033099
2025-01-01 09:45:00,2.314368,2.494409,0.271232,10.726850,-0.180041
2025-01-01 10:00:00,2.256332,2.598076,0.287155,10.239705,-0.341744
2025-01-01 10:15:00,2.018788,2.690618,0.284046,9.005798,-0.671830
2025-01-01 10:30:00,2.477289,2.771639,0.249867,11.536459,-0.294350

In [62]:
# Filter by a date range using .loc (label-based)
df_one_week = df.loc["2025-01-02":"2025-01-08"]
df_one_week.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 672 entries, 2025-01-02 00:00:00 to 2025-01-08 23:45:00
Freq: 15min
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   p_load_kw          672 non-null    float64
 1   p_pv_kw            672 non-null    float64
 2   price_eur_per_kwh  672 non-null    float64
 3   temperature_c      672 non-null    float64
 4   p_res_kw           672 non-null    float64
dtypes: float64(5)
memory usage: 31.5 KB

**Using  `loc` and `iloc`**

These two methods are among the most important tools overall.
- `loc` works **label-based** (timestamps, index names, column names)
- `iloc` works **position-based** (row numbers `0..n-1`, column positions)

For data analytics, this distinction is absolutely essential.

In [63]:
# loc with row labels and one column
sample_day = df.loc["2025-03-15", "p_load_kw"]
sample_day.head()

2025-03-15 00:00:00    2.435013
2025-03-15 00:15:00    2.499636
2025-03-15 00:30:00    2.404117
2025-03-15 00:45:00    2.320765
2025-03-15 01:00:00    2.305722
Freq: 15min, Name: p_load_kw, dtype: float64

In [64]:
# iloc with row and column positions
df.iloc[10:15, [0, 2]]

                     p_load_kw  price_eur_per_kwh
2025-01-01 02:30:00   2.336340           0.261317
2025-01-01 02:45:00   2.518412           0.230334
2025-01-01 03:00:00   2.333960           0.213380
2025-01-01 03:15:00   2.435743           0.271308
2025-01-01 03:30:00   2.500175           0.250329

In [65]:
# loc for conditional filtering
high_price_rows = df.loc[df["price_eur_per_kwh"] > 0.32, ["price_eur_per_kwh", "p_load_kw"]]
high_price_rows.head()

                     price_eur_per_kwh  p_load_kw
2025-01-17 19:15:00           0.322198   1.573566
2025-01-19 12:30:00           0.324813   1.880446
2025-01-23 13:15:00           0.323569   1.812116
2025-01-23 20:30:00           0.331133   1.462332
2025-01-24 20:30:00           0.326096   1.540531


<div class="alert alert-block alert-info">

**TASK 11**:

- Filter the DataFrame `df` using `loc` and `iloc` and provide all data where the temperature fell below 10°C. Store the result in a DataFrame called `lowTemp`.
- Create the residual load duration curve from `"p_res_kw"` and display the first 10 values.

In [66]:
## Solution 
lowTemp = df.loc[df["temperature_c"] < 10]
lowTemp.head()

,p_load_kw,p_pv_kw,price_eur_per_kwh,temperature_c,p_res_kw
2025-01-01 00:00:00,2.077939,0.0,0.278070,2.762041,2.077939
2025-01-01 00:15:00,2.212796,0.0,0.235068,1.998516,2.212796
2025-01-01 00:30:00,1.787725,0.0,0.252774,3.471822,1.787725
2025-01-01 00:45:00,2.330104,0.0,0.240243,3.405629,2.330104
2025-01-01 01:00:00,1.940196,0.0,0.213892,4.134063,1.940196

### 3.5 Quick plots (always do a quick plausibility check on data)

Visualization is the fastest way to detect errors early.
In this notebook, we use **Plotly** instead of Matplotlib for quick and interactive checks.

### Plotly mini-guide (interactive plots in Jupyter)

**Official Plotly resources**
- [Getting started with Plotly in Python](https://plotly.com/python/getting-started/)
- [Plotly Express overview](https://plotly.com/python/plotly-express/)
- [Graph Objects overview](https://plotly.com/python/graph-objects/)
- [Figure labels: title, legend, axis titles](https://plotly.com/python/figure-labels/)
- [Axes in Plotly](https://plotly.com/python/axes/)
- [Legends in Plotly](https://plotly.com/python/legend/)

**A good Plotly figure should usually contain**
1. a clear **title**
2. an **x-axis label**
3. a **y-axis label** (or two y-axis labels if you use a secondary axis)
4. a readable **legend**
5. a final `fig.show()` so the figure is displayed in the notebook

**Plotly Express (`px`) vs. Graph Objects (`go`)**
- `px` is shorter and faster for standard plots.
- `go` is more explicit and gives you finer control over each trace and layout option.

<div class="alert alert-block alert-info">

**TASK 12**:

- create another plot showing only the first 500 data points from `p_load_kw` and `price_eur_per_kwh` after the starting date `"2025-06-01"`
- use a **left y-axis** for `p_load_kw` and a **right y-axis** for `price_eur_per_kwh`
- label the plot with a meaningful title and meaningful axis labels

</div>

In [68]:
## Task 12

# Select the first 500 data points after 2025-06-01
df_subset = df.loc["2025-06-01":, ["p_load_kw", "price_eur_per_kwh"]].head(500).reset_index()

# Create a Plotly figure with a secondary y-axis
fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(
    go.Scatter(
        x=df_subset["index"],
        y=df_subset["p_load_kw"],
        mode="lines",
        name="Load",
    ),
    secondary_y=False,
)

fig.add_trace(
    go.Scatter(
        x=df_subset["index"],
        y=df_subset["price_eur_per_kwh"],
        mode="lines",
        name="Electricity price",
    ),
    secondary_y=True,
)

fig.update_layout(
    title="Load and electricity price after 2025-06-01 (first 500 data points)",
    xaxis_title="Time",
    legend_title="Signal",
)

fig.update_yaxes(title_text="Load [kW]", secondary_y=False)
fig.update_yaxes(title_text="Electricity price [€/kWh]", secondary_y=True)

fig.show()

<div class="alert alert-block alert-info">

**TASK 13**:

Create an interactive Plotly Express figure for one selected week of the year:
- plot `p_load_kw`, `p_pv_kw`, and `p_res_kw`
- add a meaningful **title**
- label both axes
- rename the legend title to `Signals`
- choose a time window where the curves are easy to compare

</div>

In [81]:
plot_df = df.loc["2025-01-01":"2025-01-07", ["p_load_kw", "p_pv_kw", "p_res_kw"]].reset_index() # note .reset_index() converts the datetime index into a regular column so the plotting function can use it explicitly as the x-axis.

fig = px.line(
    plot_df,
    x="index",
    y=["p_load_kw", "p_pv_kw", "p_res_kw"],
    title="Load, PV, and residual load (one week window)",
    labels={"index": "Time", "value": "Power [kW]", "variable": "Signal"},
)
fig.update_layout(legend_title_text="Signal")
fig.show()

<div class="alert alert-block alert-info">

**TASK 14**:

Create the same plot as in TASK 14, but this time using **`plotly.graph_objects`**:
- start with `fig = go.Figure()`
- add the traces one by one with `fig.add_trace(...)`
- set the plot title and both axis titles
- add a horizontal line at `y = 0`
- compare your `go` solution to the `px` solution: which version is shorter, and which version gives you more control?

</div>

In [82]:
plot_df = df.loc["2025-01-01":"2025-01-07", ["p_load_kw", "p_pv_kw", "p_res_kw"]].reset_index()

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=plot_df["index"],
        y=plot_df["p_load_kw"],
        mode="lines",
        name="p_load_kw",
    )
)

fig.add_trace(
    go.Scatter(
        x=plot_df["index"],
        y=plot_df["p_pv_kw"],
        mode="lines",
        name="p_pv_kw",
    )
)

fig.add_trace(
    go.Scatter(
        x=plot_df["index"],
        y=plot_df["p_res_kw"],
        mode="lines",
        name="p_res_kw",
    )
)

fig.update_layout(
    title="Load, PV, and residual load (one week window)",
    xaxis_title="Time",
    yaxis_title="Power [kW]",
    legend_title_text="Signal",
)

fig.add_hline(y=0, line_dash="dash")

fig.show()

## 4) Time-series tools you will need later

### 4.1 Resampling (e.g. 15 min → daily)

- `resample("1D").mean()` for **means**
- `resample("1D").sum()` for **sums**
- `resample("1D").agg([...])` for multiple metrics at once

In [71]:
daily_price = df["price_eur_per_kwh"].resample("1D").agg(["min", "max", "mean"])
daily_price.head()

                 min       max      mean
2025-01-01  0.211941  0.304911  0.250798
2025-01-02  0.195979  0.295352  0.248219
2025-01-03  0.216682  0.304990  0.251830
2025-01-04  0.202575  0.302643  0.254083
2025-01-05  0.195675  0.301504  0.256927

<div class="alert alert-block alert-info">

**TASK 15**:

- using the same pattern as defined above, resample the dataframe containing load, PV, and residual load (the new column you generated earlier) to a 1-hour time interval and save it to a new dataframe called `df_hourly`
- plot the result for a sample day, e.g. the birthday of your best friend
- label the axes and provide a title for the graph

</div>

In [72]:
## Solution

df_hourly = df.resample("1h").mean()

plot_hourly = df_hourly.loc["2025-06-01":"2025-06-01", ["p_load_kw", "p_pv_kw", "p_res_kw"]].reset_index()

fig = px.line(
    plot_hourly,
    x="index",
    y=["p_load_kw", "p_pv_kw", "p_res_kw"],
    title="Hourly average load, PV, and residual load on 2025-06-01",
    labels={"index": "Time", "value": "Power [kW]", "variable": "Signal"},
)
fig.show()

### 4.2 Missing values (NaN)

Real-world data often has gaps. Typical strategies are:

- `dropna()` (remove) — often not ideal for time series
- `ffill()` (*forward fill*) — propagate the previous valid value forward
- `interpolate()` — estimate intermediate values

### Plotly example for aggregated data

Aggregated results such as daily mean values or daily maxima should also be visualized briefly.

In [ ]:
daily_plot_df = daily_price.reset_index()

fig = px.line(
    daily_plot_df,
    x="index",
    y=["min", "max", "mean"],
    title="Daily electricity price statistics",
    labels={"index": "Day", "value": "Price [€/kWh]", "variable": "Metric"},
)
fig.update_layout(legend_title_text="Metric")
fig.show()

In [83]:
# Demo: create NaNs artificially
df_nan = df.copy()
df_nan.iloc[100:120, df_nan.columns.get_loc("p_load_kw")] = np.nan

print("NaNs in p_load_kw:", df_nan["p_load_kw"].isna().sum())

NaNs in p_load_kw: 20

In [75]:
df_filled = df_nan.copy()
df_filled["p_load_kw"] = df_filled["p_load_kw"].interpolate()

print("NaNs after interpolate:", df_filled["p_load_kw"].isna().sum())

NaNs after interpolate: 0

<div class="alert alert-block alert-info">

**OPTIONAL TASK 16**:

Create a **new markdown cell below** and describe in your own words what the two code blocks above do.

Your explanation should answer at least these questions:
- What is changed in `df_nan`?
- Why do missing values appear?
- What does `interpolate()` do in the second code block?
- Why is interpolation often useful for time-series analysis?

</div>

### Your answer for TASK 16

**Code block 1 (`df_nan`)**
- It creates a copy of `df` called `df_nan`.
- It changes the values in the column `p_load_kw` for rows `100` to `119` by setting them to `NaN`.
- The purpose is to simulate missing data in the load signal so you can test how your code handles gaps or incomplete time series data.

**Code block 2 (`df_filled`)**
- It creates a copy of `df_nan` called `df_filled`.
- It changes the column `p_load_kw` by filling the missing (`NaN`) values using **interpolation**.
- The purpose is to replace the artificial data gaps with estimated values so the time series becomes continuous again and can be used for plotting or further analysis.

**Why this matters for time series**
- Interpolation is useful because we can conduct anaysis and methods (e.g. battery dispatch modelling, linear programming, machine learning) with the updated data

<div class="alert alert-block alert-info">

**Integrated practice block:** The following tasks combine the tutorial content with the assignment-style tasks. Work through them after completing the examples above.

</div>

## Exercises

<div class="alert alert-block alert-info">

**TASK 17** — Residual load and PV surplus 

1. Create the residual load:
   \[
   p_{res} = p_{load} - p_{pv}
   \]
2. Filter all timestamps with **PV surplus** (`p_res < 0`).
3. Visualize a short time window and mark the surplus points.

</div>

In [76]:
## Solution
# === TASK 17 ===
# 1) Residual load
df["p_res_kw"] = df["p_load_kw"] - df["p_pv_kw"]

# 2) PV surplus moments (residual load < 0)
df_pv_surplus = df[df["p_res_kw"] < 0]

print("Number of PV surplus timesteps:", len(df_pv_surplus))

# 3) Plot a short window and highlight surplus points
window = df.loc["2025-06-01":"2025-06-03"].copy().reset_index()
surplus_window = window[window["p_res_kw"] < 0]

fig = go.Figure()
fig.add_trace(go.Scatter(x=window["index"], y=window["p_res_kw"], mode="lines", name="p_res_kw"))
fig.add_trace(go.Scatter(x=surplus_window["index"], y=surplus_window["p_res_kw"], mode="markers", name="PV surplus"))
fig.add_hline(y=0)
fig.update_layout(title="Residual load (negative = PV surplus)", xaxis_title="time", yaxis_title="kW")
fig.show()

Number of PV surplus timesteps: 9505

<div class="alert alert-block alert-info">

**TASK 18** — Analyze prices by day 

You have an electricity price time series over one year (defined above).

1. Create a **daily** DataFrame (one row per day) with `min`, `max`, and `mean`.
2. Allow a day to be selected via input.
3. Print the minimum and maximum price for that day.

</div>

In [77]:
## Solution 
# # === TASK 18 ===

# 1) Daily price table
daily_price = df["price_eur_per_kwh"].resample("1D").agg(["min", "max", "mean"])

# 2) Ask the user for a day (YYYY-MM-DD)
day_str = input("Enter a day (YYYY-MM-DD) in 2025, e.g. 2025-07-15: ").strip()

# 3) Print min/max for that day
try:
    day_row = daily_price.loc[day_str]
    print(f"Day: {day_str}")
    print(f"  Min price: {day_row['min']:.4f} €/kWh")
    print(f"  Max price: {day_row['max']:.4f} €/kWh")
except KeyError:
    print("❌ Day not found. Make sure the format is YYYY-MM-DD and within 2025.")

Day: 2025-12-12
  Min price: 0.1821 €/kWh
  Max price: 0.2974 €/kWh

<div class="alert alert-block alert-info">
<b>TASK 19</b>

Once you have completed this assessment, please:
1. make sure you **clear all plots and outputs generated** in your Jupyter notebook — in Deepnote, type `Ctrl + P` (“Project Settings”) and choose **Clear outputs of all blocks**
2. store the active (autosaved) notebook in the Deepnote file system (Deepnote copy of the Git repository)
3. **commit and push** your work to the main branch of your personalized Git repository

## 6) What comes next?

In the next notebooks, you will need exactly these building blocks again and again:

- load time series into DataFrames
- calculate KPIs
- select subsets with `loc` and `iloc`
- perform resampling
- visualize and sanity-check data

If you are comfortable with these basics, you will be very well prepared for the next analysis steps.